subtitle: ''
melody: 'original 6'
steps: 6
tempo_duration: 4
tempo_bpm: 380
second_movement: False
ensemble:
    -
        type: 'violin'
        init_transposition: 6
    -
        type: 'violin'
        init_transposition: -6
