subtitle: ''
melody: 'another 5'
target_transposition: 73
steps: 6
tempo_duration: 4
tempo_bpm: 200
second_movement: False
ensemble:
    -
        type: 'violin'
        init_transposition: 6
        start: 1
    -
        type: 'violin'
        init_transposition: -18
        start: 0
