subtitle: 'Piano & Vibraphone'
melody: 'original 5'
target_transposition: 53
steps: 6
tempo_duration: 4
tempo_bpm: 200
second_movement: False
ensemble:
    # -
    #     type: 'vibraphone'
    #     init_transposition: 6
    #     start: 1
    -
        type: 'piano'
        init_transposition: 18
        start: 2
    -
        type: 'piano'
        clef: 'bass'
        init_transposition: -18
        start: 0
parts: True
